# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: javac Lab2.java
    - name: Run my Java
      run: java Lab2
    - name: Run Build script
      run: sh build.sh     
    - name: Run Make file
      run: make
    - name: Run AWK Script 1
      run: ./Q1Script.awk Squirrel_Census.csv
    - name: Run AWK Script 2
      run: ./Q2Script.awk Squirrel_Census.csv
    - name: Run AWK Script 3
      run: ./Q3Script.awk Squirrel_Census.csv
    - name: Run AWK Script 4
      run: ./Q4Script.awk Squirrel_Census.csv
    - name: Run AWK Script 5
      run: ./Q5Script.awk Squirrel_Census.csv
